apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: weave
  namespace: weave
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`weave.megalab.cc`)
      kind: Rule
      services:
        - name: weave-scope-app
          port: 80